/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebRouteRouteImport } from './routes/_web/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as WebIndexRouteImport } from './routes/_web/index'
import { Route as WebAboutIndexRouteImport } from './routes/_web/about/index'
import { Route as AppSolarSystemSizeRouteImport } from './routes/_app/solar-system/size'
import { Route as AppSolarSystemDistanceRouteImport } from './routes/_app/solar-system/distance'

const WebRouteRoute = WebRouteRouteImport.update({
  id: '/_web',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const WebIndexRoute = WebIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebAboutIndexRoute = WebAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => WebRouteRoute,
} as any)
const AppSolarSystemSizeRoute = AppSolarSystemSizeRouteImport.update({
  id: '/solar-system/size',
  path: '/solar-system/size',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSolarSystemDistanceRoute = AppSolarSystemDistanceRouteImport.update({
  id: '/solar-system/distance',
  path: '/solar-system/distance',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WebIndexRoute
  '/solar-system/distance': typeof AppSolarSystemDistanceRoute
  '/solar-system/size': typeof AppSolarSystemSizeRoute
  '/about/': typeof WebAboutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WebIndexRoute
  '/solar-system/distance': typeof AppSolarSystemDistanceRoute
  '/solar-system/size': typeof AppSolarSystemSizeRoute
  '/about': typeof WebAboutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_web': typeof WebRouteRouteWithChildren
  '/_web/': typeof WebIndexRoute
  '/_app/solar-system/distance': typeof AppSolarSystemDistanceRoute
  '/_app/solar-system/size': typeof AppSolarSystemSizeRoute
  '/_web/about/': typeof WebAboutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/solar-system/distance' | '/solar-system/size' | '/about/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/solar-system/distance' | '/solar-system/size' | '/about'
  id:
    | '__root__'
    | '/_app'
    | '/_web'
    | '/_web/'
    | '/_app/solar-system/distance'
    | '/_app/solar-system/size'
    | '/_web/about/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  WebRouteRoute: typeof WebRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_web': {
      id: '/_web'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/': {
      id: '/_web/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/about/': {
      id: '/_web/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof WebAboutIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_app/solar-system/size': {
      id: '/_app/solar-system/size'
      path: '/solar-system/size'
      fullPath: '/solar-system/size'
      preLoaderRoute: typeof AppSolarSystemSizeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/solar-system/distance': {
      id: '/_app/solar-system/distance'
      path: '/solar-system/distance'
      fullPath: '/solar-system/distance'
      preLoaderRoute: typeof AppSolarSystemDistanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppSolarSystemDistanceRoute: typeof AppSolarSystemDistanceRoute
  AppSolarSystemSizeRoute: typeof AppSolarSystemSizeRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSolarSystemDistanceRoute: AppSolarSystemDistanceRoute,
  AppSolarSystemSizeRoute: AppSolarSystemSizeRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface WebRouteRouteChildren {
  WebIndexRoute: typeof WebIndexRoute
  WebAboutIndexRoute: typeof WebAboutIndexRoute
}

const WebRouteRouteChildren: WebRouteRouteChildren = {
  WebIndexRoute: WebIndexRoute,
  WebAboutIndexRoute: WebAboutIndexRoute,
}

const WebRouteRouteWithChildren = WebRouteRoute._addFileChildren(
  WebRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  WebRouteRoute: WebRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
