/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebRouteRouteImport } from './routes/_web/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as WebIndexRouteImport } from './routes/_web/index'
import { Route as WebTeacherIndexRouteImport } from './routes/_web/teacher/index'
import { Route as WebAboutIndexRouteImport } from './routes/_web/about/index'
import { Route as AppSolarSystemSizeIndexRouteImport } from './routes/_app/solar-system/size/index'
import { Route as AppSolarSystemDistanceIndexRouteImport } from './routes/_app/solar-system/distance/index'

const WebRouteRoute = WebRouteRouteImport.update({
  id: '/_web',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const WebIndexRoute = WebIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebTeacherIndexRoute = WebTeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebAboutIndexRoute = WebAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => WebRouteRoute,
} as any)
const AppSolarSystemSizeIndexRoute = AppSolarSystemSizeIndexRouteImport.update({
  id: '/solar-system/size/',
  path: '/solar-system/size/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSolarSystemDistanceIndexRoute =
  AppSolarSystemDistanceIndexRouteImport.update({
    id: '/solar-system/distance/',
    path: '/solar-system/distance/',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WebIndexRoute
  '/about/': typeof WebAboutIndexRoute
  '/teacher/': typeof WebTeacherIndexRoute
  '/solar-system/distance/': typeof AppSolarSystemDistanceIndexRoute
  '/solar-system/size/': typeof AppSolarSystemSizeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WebIndexRoute
  '/about': typeof WebAboutIndexRoute
  '/teacher': typeof WebTeacherIndexRoute
  '/solar-system/distance': typeof AppSolarSystemDistanceIndexRoute
  '/solar-system/size': typeof AppSolarSystemSizeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_web': typeof WebRouteRouteWithChildren
  '/_web/': typeof WebIndexRoute
  '/_web/about/': typeof WebAboutIndexRoute
  '/_web/teacher/': typeof WebTeacherIndexRoute
  '/_app/solar-system/distance/': typeof AppSolarSystemDistanceIndexRoute
  '/_app/solar-system/size/': typeof AppSolarSystemSizeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/'
    | '/teacher/'
    | '/solar-system/distance/'
    | '/solar-system/size/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/teacher'
    | '/solar-system/distance'
    | '/solar-system/size'
  id:
    | '__root__'
    | '/_app'
    | '/_web'
    | '/_web/'
    | '/_web/about/'
    | '/_web/teacher/'
    | '/_app/solar-system/distance/'
    | '/_app/solar-system/size/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  WebRouteRoute: typeof WebRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_web': {
      id: '/_web'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/': {
      id: '/_web/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/teacher/': {
      id: '/_web/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof WebTeacherIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/about/': {
      id: '/_web/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof WebAboutIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_app/solar-system/size/': {
      id: '/_app/solar-system/size/'
      path: '/solar-system/size'
      fullPath: '/solar-system/size/'
      preLoaderRoute: typeof AppSolarSystemSizeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/solar-system/distance/': {
      id: '/_app/solar-system/distance/'
      path: '/solar-system/distance'
      fullPath: '/solar-system/distance/'
      preLoaderRoute: typeof AppSolarSystemDistanceIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppSolarSystemDistanceIndexRoute: typeof AppSolarSystemDistanceIndexRoute
  AppSolarSystemSizeIndexRoute: typeof AppSolarSystemSizeIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSolarSystemDistanceIndexRoute: AppSolarSystemDistanceIndexRoute,
  AppSolarSystemSizeIndexRoute: AppSolarSystemSizeIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface WebRouteRouteChildren {
  WebIndexRoute: typeof WebIndexRoute
  WebAboutIndexRoute: typeof WebAboutIndexRoute
  WebTeacherIndexRoute: typeof WebTeacherIndexRoute
}

const WebRouteRouteChildren: WebRouteRouteChildren = {
  WebIndexRoute: WebIndexRoute,
  WebAboutIndexRoute: WebAboutIndexRoute,
  WebTeacherIndexRoute: WebTeacherIndexRoute,
}

const WebRouteRouteWithChildren = WebRouteRoute._addFileChildren(
  WebRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  WebRouteRoute: WebRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
